// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST10256859_PROG7311_POE.DataBase;

#nullable disable

namespace ST10256859_PROG7311_POE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514202434_SeedProductImages")]
    partial class SeedProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ST10256859_PROG7311_POE.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Address = "13 Nautilis Drive",
                            Email = "jenna@gmail.com",
                            FirstName = "Jenna",
                            LastName = "Kemm",
                            Password = "password123",
                            PhoneNumber = "1234567899"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Address = "14 Jumper Drive",
                            Email = "kayla@gmail.com",
                            FirstName = "Kayla",
                            LastName = "Ferr",
                            Password = "password123",
                            PhoneNumber = "1001001000"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Address = "15 Ocean Drive",
                            Email = "lucas@gmail.com",
                            FirstName = "Lucas",
                            LastName = "Miller",
                            Password = "password123",
                            PhoneNumber = "1112223333"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Address = "16 River Road",
                            Email = "sophia@gmail.com",
                            FirstName = "Sophia",
                            LastName = "Wilson",
                            Password = "password123",
                            PhoneNumber = "2223334444"
                        },
                        new
                        {
                            EmployeeID = 5,
                            Address = "17 Forest Lane",
                            Email = "ethan@gmail.com",
                            FirstName = "Ethan",
                            LastName = "Moore",
                            Password = "password123",
                            PhoneNumber = "3334445555"
                        },
                        new
                        {
                            EmployeeID = 6,
                            Address = "18 Mountain Ave",
                            Email = "isabella@gmail.com",
                            FirstName = "Isabella",
                            LastName = "Taylor",
                            Password = "password123",
                            PhoneNumber = "4445556666"
                        },
                        new
                        {
                            EmployeeID = 7,
                            Address = "19 Valley Blvd",
                            Email = "aiden@gmail.com",
                            FirstName = "Aiden",
                            LastName = "Anderson",
                            Password = "password123",
                            PhoneNumber = "5556667777"
                        },
                        new
                        {
                            EmployeeID = 8,
                            Address = "20 Lake Street",
                            Email = "mia@gmail.com",
                            FirstName = "Mia",
                            LastName = "Thomas",
                            Password = "password123",
                            PhoneNumber = "6667778888"
                        });
                });

            modelBuilder.Entity("ST10256859_PROG7311_POE.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FarmerID");

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            FarmerID = 1,
                            Address = "65 Ringwood Drive",
                            Email = "dhiren@gmail.com",
                            FirstName = "Dhiren",
                            LastName = "Ruthenavelu",
                            Password = "password123",
                            PhoneNumber = "1234567899"
                        },
                        new
                        {
                            FarmerID = 2,
                            Address = "456 Oak Avenue",
                            Email = "chad@gmail.com",
                            FirstName = "Chad",
                            LastName = "Fairlie",
                            Password = "password123",
                            PhoneNumber = "2137465899"
                        },
                        new
                        {
                            FarmerID = 3,
                            Address = "789 Pine Street",
                            Email = "ava@gmail.com",
                            FirstName = "Ava",
                            LastName = "Smith",
                            Password = "password123",
                            PhoneNumber = "3216549870"
                        },
                        new
                        {
                            FarmerID = 4,
                            Address = "101 Maple Lane",
                            Email = "liam@gmail.com",
                            FirstName = "Liam",
                            LastName = "Johnson",
                            Password = "password123",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            FarmerID = 5,
                            Address = "202 Cedar Road",
                            Email = "olivia@gmail.com",
                            FirstName = "Olivia",
                            LastName = "Williams",
                            Password = "password123",
                            PhoneNumber = "5551234567"
                        },
                        new
                        {
                            FarmerID = 6,
                            Address = "303 Birch Blvd",
                            Email = "noah@gmail.com",
                            FirstName = "Noah",
                            LastName = "Brown",
                            Password = "password123",
                            PhoneNumber = "4449876543"
                        },
                        new
                        {
                            FarmerID = 7,
                            Address = "404 Spruce Ave",
                            Email = "emma@gmail.com",
                            FirstName = "Emma",
                            LastName = "Jones",
                            Password = "password123",
                            PhoneNumber = "3334567890"
                        },
                        new
                        {
                            FarmerID = 8,
                            Address = "505 Willow Way",
                            Email = "mason@gmail.com",
                            FirstName = "Mason",
                            LastName = "Davis",
                            Password = "password123",
                            PhoneNumber = "2223456789"
                        });
                });

            modelBuilder.Entity("ST10256859_PROG7311_POE.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FarmerID")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProductImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.HasIndex("FarmerID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            AvailableQuantity = 50,
                            Category = "Vegetable",
                            Description = "Fresh and ripe tomatoes.",
                            FarmerID = 1,
                            ProductName = "Tomatoes",
                            ProductPrice = 15.99m,
                            ProductionDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 2,
                            AvailableQuantity = 80,
                            Category = "Vegetable",
                            Description = "Crunchy orange carrots.",
                            FarmerID = 1,
                            ProductName = "Carrots",
                            ProductPrice = 10.50m,
                            ProductionDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 3,
                            AvailableQuantity = 100,
                            Category = "Fruit",
                            Description = "Sweet red apples.",
                            FarmerID = 2,
                            ProductName = "Apples",
                            ProductPrice = 20.00m,
                            ProductionDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 4,
                            AvailableQuantity = 40,
                            Category = "Vegetable",
                            Description = "Crisp green lettuce.",
                            FarmerID = 2,
                            ProductName = "Lettuce",
                            ProductPrice = 8.75m,
                            ProductionDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 5,
                            AvailableQuantity = 60,
                            Category = "Vegetable",
                            Description = "Organic potatoes.",
                            FarmerID = 3,
                            ProductName = "Potatoes",
                            ProductPrice = 12.00m,
                            ProductionDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 6,
                            AvailableQuantity = 30,
                            Category = "Fruit",
                            Description = "Juicy strawberries.",
                            FarmerID = 3,
                            ProductName = "Strawberries",
                            ProductPrice = 25.00m,
                            ProductionDate = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 7,
                            AvailableQuantity = 70,
                            Category = "Vegetable",
                            Description = "Fresh cucumbers.",
                            FarmerID = 4,
                            ProductName = "Cucumbers",
                            ProductPrice = 9.50m,
                            ProductionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 8,
                            AvailableQuantity = 25,
                            Category = "Fruit",
                            Description = "Wild blueberries.",
                            FarmerID = 4,
                            ProductName = "Blueberries",
                            ProductPrice = 30.00m,
                            ProductionDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 9,
                            AvailableQuantity = 55,
                            Category = "Vegetable",
                            Description = "Colorful peppers.",
                            FarmerID = 5,
                            ProductName = "Peppers",
                            ProductPrice = 14.00m,
                            ProductionDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 10,
                            AvailableQuantity = 90,
                            Category = "Fruit",
                            Description = "Sweet bananas.",
                            FarmerID = 5,
                            ProductName = "Bananas",
                            ProductPrice = 18.00m,
                            ProductionDate = new DateTime(2025, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 11,
                            AvailableQuantity = 35,
                            Category = "Vegetable",
                            Description = "Leafy spinach.",
                            FarmerID = 6,
                            ProductName = "Spinach",
                            ProductPrice = 11.00m,
                            ProductionDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 12,
                            AvailableQuantity = 65,
                            Category = "Fruit",
                            Description = "Citrus oranges.",
                            FarmerID = 6,
                            ProductName = "Oranges",
                            ProductPrice = 22.00m,
                            ProductionDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 13,
                            AvailableQuantity = 45,
                            Category = "Vegetable",
                            Description = "Green broccoli.",
                            FarmerID = 7,
                            ProductName = "Broccoli",
                            ProductPrice = 13.00m,
                            ProductionDate = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 14,
                            AvailableQuantity = 75,
                            Category = "Fruit",
                            Description = "Seedless grapes.",
                            FarmerID = 7,
                            ProductName = "Grapes",
                            ProductPrice = 28.00m,
                            ProductionDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 15,
                            AvailableQuantity = 85,
                            Category = "Vegetable",
                            Description = "Red onions.",
                            FarmerID = 8,
                            ProductName = "Onions",
                            ProductPrice = 7.50m,
                            ProductionDate = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductID = 16,
                            AvailableQuantity = 60,
                            Category = "Fruit",
                            Description = "Juicy pears.",
                            FarmerID = 8,
                            ProductName = "Pears",
                            ProductPrice = 19.00m,
                            ProductionDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ST10256859_PROG7311_POE.Models.Product", b =>
                {
                    b.HasOne("ST10256859_PROG7311_POE.Models.Farmer", "Farmer")
                        .WithMany("Products")
                        .HasForeignKey("FarmerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("ST10256859_PROG7311_POE.Models.Farmer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
